name: zmp3chart
description: Zing MP3 Chart by LamNDT
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  audioplayers: ^5.0.0
  json_annotation: ^4.3.0
  retrofit: ^4.0.1
  retrofit_generator: ^7.0.8
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
